### ISSUE TITLE
Issue: virt-install check fails on version 0.10.0

### ISSUE THREAD

**Issue by a-nldisr** [cobbler/koan#5]
Today i performed an install with Centos 7.1406, installed a libvirt/kvm host and installed koan from epel7 (issue occurs with repo's from cobbler website as well)

When i give command: 
```sh
koan --server=cobbler --system=random_VM --virt
```

Following error occurs: 
```sh
- ['/usr/bin/virt-install', '--version']
need python-virtinst >= 0.2 or virt-install package to do installs for qemu/kvm (depending on your OS)
```

Installed versions: 
```sh 
3.10.0-123.20.1.el7.x86_64
```

```sh
koan-2.6.7-13.1.noarch
```

virsh version:
```sh
Compiled against library: libvirt 1.1.1
Using library: libvirt 1.1.1
Using API: QEMU 1.1.1
Running hypervisor: QEMU 2.0.0
```

```sh
 virt-install --version
0.10.0
```

When uncommenting section related to this: 
https://github.com/cobbler/koan/blob/619f082cddf9e5205354ec1a57abfb62eac5df4c/koan/app.py#L738
The virtual machine starts and kickstarts without any issue. 

Issue is reproducable every time.

**Comment by dblommesteijn** [comment]
The code snippet below is a better solution for version checking:

```python
def cmp_greater_or_equal(a, b):
   ass = a.split(".")
   bss = b.split(".")
   if len(ass) != 3 or len(bss) != 3:
       raise Exception("expected version format: `x.x.x`")
   for i, a in enumerate(ass):
       a = int(a)
       b = int(bss[i])
       if a < b:
           return False
   return True
```

**Comment by dblommesteijn** [comment]
@jmaas Would you like me to make it into a pull-request?

**Comment by jmaas** [comment]
That would be great!! I'm really too busy with real-life stuff these days. Any help is much appreciated.

In your opinion, would this fix warrant a bugfix release of Koan ?

**Comment by dblommesteijn** [comment]
Guess so, because double version digits are not supported as it is now.

**Comment by jmaas** [comment]
Okay, will you do the backport to release26 branch as well ?
Then i'll do another release (2.6.8) this week.

Thanks!

On Tue, Mar 31, 2015 at 10:16 AM, Dennis Blommesteijn <
notifications@github.com> wrote:

> Guess so, because double version digits are not supported as it is now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbler/koan/issues/5#issuecomment-87991484>.
>



-- 
Grtz,
Jörgen Maas

**Comment by jmaas** [comment]
Merged into master and release26 branches. Closing issue.

**Comment by wulfgarpro** [comment]
I've come across a similar issue with release26 branch. 

> cat /etc/os-release 
NAME="Ubuntu"
VERSION="15.10 (Wily Werewolf)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.10"
VERSION_ID="15.10"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

> dpkg -l | grep virtinst
ii  virtinst                                                    1:1.0.1-5ubuntu2                           all          Programs to create and clone virtual machines

> which virt-install
/usr/bin/virt-install

> virt-install --version
1.0.1

> sudo koan --server=172.17.0.5 --virt --system=example-vm --virt-type=kvm       
- looking for Cobbler at http://172.17.0.5:80/cobbler_api
install_tree: http://172.17.0.5/cblr/links/SLES-11-SP3-x86_64
- ['/usr/bin/virt-install', '--version']
1.0.1
<type 'exceptions.Exception'>
expected version format differs
  File "/usr/local/lib/python2.7/dist-packages/koan/app.py", line 274, in main
    k.run()
   File "/usr/local/lib/python2.7/dist-packages/koan/app.py", line 424, in run
    self.virt()
   File "/usr/local/lib/python2.7/dist-packages/koan/app.py", line 844, in virt
    return self.net_install(after_download)
   File "/usr/local/lib/python2.7/dist-packages/koan/app.py", line 636, in net_install
    if len(version_str) == 0 and not utils.check_version_greater_or_equal(version_str.strip(), "0.2.0"):
   File "/usr/local/lib/python2.7/dist-packages/koan/utils.py", line 589, in check_version_greater_or_equal
    raise Exception("expected version format differs")

**Comment by dblommesteijn** [comment]
@wulfgarpro as you can see you're using an old version of koan.

**Comment by wulfgarpro** [comment]
@dblommesteijn it's Koan from release26; hasn't the fix been merged?

**Comment by dblommesteijn** [comment]
@wulfgarpro according to your line of code: `if len(version_str) == 0 and not utils.check_version_greater_or_equal(version_str.strip(), "0.2.0"):` it's not packed into the 26 release.

PS. I'm not the developer of koan, I've only made this fix.

**Comment by dblommesteijn** [comment]
@wulfgarpro On closer inspection there was an error with my check: #16

**Comment by wulfgarpro** [comment]
@dblommesteijn thanks

**Comment by celesteking** [comment]
Can we finally push this to EPEL or whatever so Koan actually works on EL7 nodes? Tnx.
