### ISSUE TITLE
ks_meta and possibly other variables have been renamed in Cobbler git

### ISSUE THREAD

**Issue by nacc** [cobbler/koan#9]
It is now autoinstall_meta, I'm sure there is going to be other breakage.

**Comment by alanoe** [comment]
nacc, that renaming was done in master 6 months ago, so there is no new "breakage". 

That issue description does not help much. Could you describe what was broken?

**Comment by nacc** [comment]
koan is now maintained outside of cobbler, so if you try and use mainline koan with mainline cobbler it fails pretty badly.

koan has knowledge of cobbler's internals, including the various names used in the profile metadata. As I said, "ks_meta" is now "autoinstall_meta".

**Comment by alanoe** [comment]
much clearer now, thanks for the feedback

**Comment by nacc** [comment]
here's what I had to do (so far):

--- a/koan/app.py
+++ b/koan/app.py
@@ -56,7 +56,7 @@ DISPLAY_PARAMS = [
     "distro",
     "profile",
     "autoinst",
-    "ks_meta",
+    "autoinstall_meta",
     "install_tree",
     "kernel",
     "initrd",
@@ -627,30 +627,38 @@ class Koan:
             # fix URLs
             if profile_data["autoinst"][0] == "/":
                 if not self.system:
-                    profile_data["autoinst"] = "http://%s/cblr/svc/op/ks/profile/%s" % (
+                    profile_data["autoinst"] = "http://%s/cblr/svc/op/autoinstall/profile/%s" % (
                         profile_data['http_server'], profile_data['name'])
                 else:
-                    profile_data["autoinst"] = "http://%s/cblr/svc/op/ks/system/%s" % (
+                    profile_data["autoinst"] = "http://%s/cblr/svc/op/autoinstall/system/%s" % (
                         profile_data['http_server'], profile_data['name'])
@@ -789,9 +804,9 @@ class Koan:
         try:
             if profile_data["autoinst"][:4] == "http":
                 if not self.system:
-                    url_fmt = "http://%s/cblr/svc/op/ks/profile/%s"
+                    url_fmt = "http://%s/cblr/svc/op/autoinstall/profile/%s"
                 else:
-                    url_fmt = "http://%s/cblr/svc/op/ks/system/%s"
+                    url_fmt = "http://%s/cblr/svc/op/autoinstall/system/%s"
                 url = url_fmt % (self.server, profile_data['name'])
             else:
                 url = profile_data["autoinst"]
 
     def get_install_tree_from_profile_data(self, profile_data):
         """
-        Split ks_meta to obtain the tree path. Generate the install_tree
-           using the http_server and the tree obtained from splitting ks_meta
+        Split autoinstall_meta to obtain the tree path. Generate the install_tree
+           using the http_server and the tree obtained from splitting autoinstall_meta
 
         """
 
         try:
-            tree = profile_data["ks_meta"].split()
-            # Ensure we only take the tree in case ks_meta args are passed
-            # First check for tree= in ks_meta arguments
+            tree = profile_data["autoinstall_meta"].split()
+            # Ensure we only take the tree in case autoinstall_meta args are passed
+            # First check for tree= in autoinstall_meta arguments
             meta_re = re.compile('tree=')
             tree_found = ''
             for entry in tree:

**Comment by SchoolGuy** [comment]
In the new Cobbler 3.0 we tried to make it happen that most of the code works with an older koan so this shouldn't be a problem. The tests which were done by me did not have any problems with that. If there are some I have overseen please reopen!
